import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/product.module.css';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Image from 'next/image';
import Link from 'next/link';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>SITENAME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <Header />
      <main >
        
        <h1 className={styles.title}>ポートフォリオ</h1>

        <div className={styles.device}>
            <h2>iosアプリ</h2>

            <div className={styles.productConten}>
                <div className={styles.productItem}>
                  <Link href="https://nogizakaquiz.com">
                    <strong>乃木チェック</strong>
                    <div>
                      <Image src="/nogicheck.jpeg" width={100} height={100} />
                    </div>   
                  </Link>             
                </div>

                <div className={styles.productItem}>
                    <strong>妄想打線クリエイト</strong>
                    <div>
                      <Image src="/dasen.png" width={100} height={100} />
                    </div>
                </div>
            </div>
        </div>


        <div className={styles.device}>
            <h2>ウェブアプリ</h2>

            <div className={styles.productConten}>
                <div className={styles.productItem}>
                  <Link href="https://nogizakaquiz.com">
                      <strong>乃木坂クイズタウン</strong>
                      <div>
                        <Image src="/nogizaka.jpeg" width={100} height={100} />
                      </div>  
                  </Link>              
                </div>

                <div className={styles.productItem}>
                  <Link href="https://kpop-sort.com">
                    <strong>Kpop-girls ソート</strong>
                    <div>
                      <Image src="/kpop.jpeg" width={100} height={100} />
                    </div>
                  </Link>
                </div>
            </div>
        </div>
        

        
      </main>

      <Footer/>
    </div>
  )
}
